In [1]:
import numpy as np

In [2]:
data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])

Task - 1 : Print the shape of data. Then compute and print the mean temperature per station (one value per row).

In [20]:
print(f"Shape Of The Data : {data.shape}\n")

means = data.mean(axis=1)

for i in range(len(means)):
  print(f"Mean Temperature Station {i+1} : {round(means[i],2)}")

Shape Of The Data : (4, 5)

Mean Temperature Station 1 : 25.3
Mean Temperature Station 2 : 23.78
Mean Temperature Station 3 : 26.58
Mean Temperature Station 4 : 25.26


Task - 2 : Using a boolean mask, extract all temperature readings above 28.0°C and print them as a 1D array.

In [32]:
print(f"Temperature Above 28.0°C : {data[data > 28.0]}")

Temperature Above 28.0°C : [31.2 28.7 30.5 33.1 29.6 31.9 28.1]


Task - 3 : Normalize the entire data array to the range [0, 1] using the formula below and print the result rounded to 2 decimal places : normalized = (data - data.min()) / (data.max() - data.min())


In [48]:
normalized = ((data - data.min()) / (data.max() - data.min())).round(2)
print(f"Normalized Data : {normalized}")

Normalized Data : [[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
